### PR TITLE
small things

### PR DESCRIPTION
**Pull request by di-effe**
**epitaph**
I realized to late the theme had replaced my config.toml and had a little panic attack :D
Now the script creates a bak copy of the original file.

**config.toml**
Keybindings for scripts were pointing at ~/.config/leftwm/themes/epitaph (lowercase) while the theme in cloned into ~/.config/leftwm/themes/Epitaph (capitalzied)

### CODE REVIEW

**Comment by VentGrey** [comment]
Nice! I think the lowercase was because my folder was named like that when I first forked Blue Coffee. Thank you so much for your PR!

**Review by VentGrey — CHANGES_REQUESTED** [review]
Just as a small note. Can you try to remove the compiled binaries and the `.installed` file? It's to prevent breakages after merging this PR :)

**Comment by di-effe** [comment]
Dang, I thought they were in gitignore :D

**Comment by di-effe** [comment]
Better now?

**Review by VentGrey — APPROVED** [review]
Looks Perfect!

**Pull request merged**
